/**
 * Martin Egli
 * 2023-03-21
 * define io
 */

#ifndef _IO_H_
#define _IO_H_

#include <avr/io.h>

// LED1: PA3
#define LED1_PORT	PORTA
#define LED1_PIN	3
#define LED1_PIN_BV	_BV(LED1_PIN)
// LED2: PA2
#define LED2_PORT	PORTA
#define LED2_PIN	2
#define LED2_PIN_BV	_BV(LED2_PIN)
// LED3: PB0
#define LED3_PORT	PORTB
#define LED3_PIN	0
#define LED3_PIN_BV	_BV(LED3_PIN)
// LED4: PB1
#define LED4_PORT	PORTB
#define LED4_PIN	1
#define LED4_PIN_BV	_BV(LED4_PIN)

// BUTTON1: PA5
#define BUTTON1_PORT	PORTA
#define BUTTON1_PIN		5
#define BUTTON1_PIN_BV	_BV(BUTTON1_PIN)
#define BUTTON1_PIN_CTRL	PIN##5##CTRL
// BUTTON2: PA4
#define BUTTON2_PORT	PORTA
#define BUTTON2_PIN		4
#define BUTTON2_PIN_BV	_BV(BUTTON2_PIN)
#define BUTTON2_PIN_CTRL	PIN##4##CTRL
// BUTTON3: PB2
#define BUTTON3_PORT	PORTB
#define BUTTON3_PIN		2
#define BUTTON3_PIN_BV	_BV(BUTTON2_PIN)
#define BUTTON3_PIN_CTRL	PIN##2##CTRL
// BUTTON4: PB3
#define BUTTON4_PORT	PORTB
#define BUTTON4_PIN		3
#define BUTTON4_PIN_BV	_BV(BUTTON4_PIN)
#define BUTTON4_PIN_CTRL	PIN##3##CTRL

// DBG1: PA1 (TxD, alternate)
#define DBG1_PORT	    PORTA
#define DBG1_PIN		1
#define DBG1_PIN_BV		_BV(DBG1_PIN)
#define DBG1_DIR_OUT()  DBG1_PORT.DIRSET = DBG1_PIN_BV
#define DBG1_PIN_SET()  DBG1_PORT.OUTSET = DBG1_PIN_BV
#define DBG1_PIN_CLR()  DBG1_PORT.OUTCLR = DBG1_PIN_BV

// DBG2: PA6
#define DBG2_PORT	    PORTA
#define DBG2_PIN		6
#define DBG2_PIN_BV		_BV(DBG2_PIN)
#define DBG2_DIR_OUT()  DBG2_PORT.DIRSET = DBG2_PIN_BV
#define DBG2_PIN_SET()  DBG2_PORT.OUTSET = DBG2_PIN_BV
#define DBG2_PIN_CLR()  DBG2_PORT.OUTCLR = DBG2_PIN_BV

// DBG3: PA7
#define DBG3_PORT	    PORTA
#define DBG3_PIN		7
#define DBG3_PIN_BV		_BV(DBG3_PIN)
#define DBG3_DIR_OUT()  DBG3_PORT.DIRSET = DBG3_PIN_BV
#define DBG3_PIN_SET()  DBG3_PORT.OUTSET = DBG3_PIN_BV
#define DBG3_PIN_CLR()  DBG3_PORT.OUTCLR = DBG3_PIN_BV

#endif
